### ISSUE TITLE
Versions should be handled in the client

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/kinto.js#11]
Currently, Cliquetis handles the version in the host url, with a prefix (e.g. `http://localhost:8888/v1`).

It's important to have a way to tell which version of the protocol is supported by Cliquetis, in order to detect potential problems due to version mismatches.

To do so, I believe a request to the / endpoint of the server should be made, to get the protocol version, and then check that the protocol is the same as the one of Cliquetis.

**Comment by Natim** [comment]
I think the version of Kinto bind to a version of the protocol. We won't have an update of the protocol without an update of Kinto.

In that case I think it is sufficient to force the version of kinto into the version of Cliquetis.

**Comment by ametaireau** [comment]
I think it will do what we want, yes!

**Comment by leplatrem** [comment]
Related: 
* https://github.com/mozilla-services/cliquet/pull/341
* https://github.com/mozilla-services/cliquet/issues/324
* https://github.com/mozilla-services/cliquet/issues/334
* #37

**Comment by n1k0** [comment]
> In that case I think it is sufficient to force the version of kinto into the version of Cliquetis.

This is what has been implemented since, closing.
