### ISSUE TITLE
Handle BATCH 409 responses

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto.js#14]
Handle 409 response when uniqueness rule is violated (eg. `POST` with existing `id`, unique field, etc.)

**Comment by n1k0** [comment]
Trying to come with test cases for this, I realized there are none using Kinto:

- We don't do any POST providing an id;
- Kinto server doesn't define any unicity constraint rule.

I'm closing this for now, we shall reopen if we ever want to move to client-side schema definition someday.

**Comment by leplatrem** [comment]
+1 for closing. This issue was still valid when kinto.js was named *cliquetis.js* and was supposed to handle any kind of cliquet application.
