### ISSUE TITLE
Validate passed uuids

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto.js#28]
This would apply to `#get()`, `#update()`, `#delete()` and `#resolve()`. We should throw when an id doesn't match the UUID format. Tests would have to be updated accordingly.

For `#resolve()`, we should also validate that the resolution object uuid matches the one from the conflict, and reject accordingly.

**Comment by Natim** [comment]
I am not sure we want to force uuid for record_id.

**Comment by n1k0** [comment]
> I am not sure we want to force uuid for record_id.

Well, Cliquetis will generate them upon local creation. I suspect we're tied to them, at least in the client.

**Comment by Natim** [comment]
> I suspect we're tied to them, at least in the client.

What if you are using Cliquetis with a server that doesn't create records using a UUID?
As it may be the case with payments.

**Comment by n1k0** [comment]
I'm realizing that while Cliquetis intends to be used offline-first, existing data can still come from a server at first sync, and we can't really predict the id format they're using. 

So that raises an interesting point, ho can we notify the client of the id format it should use? Should we distinguish locally created ids from remote ones?

**Comment by Natim** [comment]
I think we should not do any assumption on the id format and use any existing ids.
For creating local record, we should continue with uuid.

In the future we may also provide a way to plug other names generators.

Another way to do that, would be to create records using a POST rather than a PUT and to update the local generated ID after the creation with the remote server id.

**Comment by n1k0** [comment]
>  For creating local record, we should continue with uuid.

So we'll be sending uuid to servers possibly not using that format?

> Another way to do that, would be to create records using a POST rather than a PUT and to update the local generated ID after the creation with the remote server id.

Sounds like a (complicated) plan.

**Comment by n1k0** [comment]
Silly thought: why don't we enforce the uuid format in kinto?

**Comment by Natim** [comment]
> So we'll be sending uuid to servers possibly not using that format?

No I mean, we will send uuid anyway and the server will accept it but we may receive other kind of ids from the server.

**Comment by n1k0** [comment]
Hmm, would that mean we'd possibly mix different primary key formats between client and servers? Seems odd to me.

Sample scenario:

- client fetches changes, receive records using integers as primary key identifiers, stores them locally
- client creates new records, using the uuid v4 format
- push them to the server, server stores them using that format
- both client and servers now have records using two different id formats

I think we should distinguish between server ids and local ones. That's a rather consequent change, though I can't see any other way around preventing that situation :/

**Comment by Natim** [comment]
> Silly thought: why don't we enforce the uuid format in kinto? 

I think a the records level it is the case at the moment. And it is always possible to do a md5 from a string in order to get a guessable UUID

**Comment by ametaireau** [comment]
Rather than guessing what the server does, we should ask it!

It should be possible to ask what is the generator function used for a specific bucket / collection, or even service.

**Comment by Natim** [comment]
This answer makes me wonder: What is the problem are we trying to solve with this issue?

**Comment by n1k0** [comment]
> What is the problem are we trying to solve with this issue?

Consistency?

**Comment by Natim** [comment]
Isn't the server responsible for consistency?

**Comment by n1k0** [comment]
Sounds good, so we need to find a way for the server to expose its id format so the client can reflect that for new record it creates and push.

**Comment by n1k0** [comment]
Note that enforcing the uuid convention for both client & server solves just that, the easy way, and I'm not finding it very limiting.

**Comment by Natim** [comment]
I have opened https://github.com/mozilla-services/kinto/issues/102 to discuss this.
I see the benefits but I am not sure to see all the impacts of this decision.
