### ISSUE TITLE
Host a demo instance on Github pages

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto.js#38]

**Comment by n1k0** [comment]
`git subtree push --prefix demo origin gh-pages` should work, and actually created the branch with appropriate files, but nothing shows up.

Could this be because I'm not an admin of the repository?

**Comment by n1k0** [comment]
Ah, just received an email about that:

> The page build failed with the following error:
>
>The symbolic link `/kinto.dev.js` targets a file which does not exist within your site's repository. For more information, see https://help.github.com/articles/page-build-failed-symlink-does-not-exist-within-your-site-s-repository.
>
>If you have any questions you can contact us by replying to this email.

**Comment by n1k0** [comment]
Fixed: http://mozilla-services.github.io/kinto.js/

Though it's now blocked by https://github.com/mozilla-services/kinto/issues/139

**Comment by Natim** [comment]
The certificate has been fixed. Also I still see an error with the demo:

```HTTP304 - SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data```

**Comment by Natim** [comment]
I have openned https://github.com/mozilla-services/kinto.js/issues/71 for this specific error.

**Comment by n1k0** [comment]
So this is a Cliquet bug, which doesn't expose the `Content-Length` header in CORS allowed ones.

**Comment by Natim** [comment]
Refs https://github.com/mozilla-services/cliquet/pull/390/files
