### ISSUE TITLE
Error on synchronization with a HTTP 304 on the collection from the server

### ISSUE THREAD

**Issue by Natim** [mozilla-services/kinto.js#71]
```HTTP304 - SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data```

**Comment by n1k0** [comment]
Grmbl, seems code is trying to parse an empty response here.

**Comment by Natim** [comment]
yes

**Comment by n1k0** [comment]
So for some reason, server is no more sending the `Content-Length` header in 304 responses, while I swear it was the case some times ago. The http `request()` function relies on this header combined with status code to detect if response JSON body is missing. Hints?

**Comment by Natim** [comment]
refs https://github.com/mozilla-services/cliquet/pull/390/files
